main/urls.py
#django import
from django.urls import path

#my import 
from . import views
from .views import Quizzes

app_name="main"
urlpatterns = [
        path("quizzes/",Quizzes.as_view(),name="home"),
        path("question/<int:quiz_id>/",views.question,name="question"),
        path("submit/<int:quiz_id>/",views.submit,name="submit")
        ]

quiz/urls.py
#django import
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("main.urls")),
]

main/models.py
#django import 
from django.db import models
from django.contrib.auth.models import User


LEVEL = (
        ("Hard","Hard"),
        ("Easy","Easy"),
        ("Normal","Normal"),
        )
class Quiz(models.Model):
    name:str = models.CharField(max_length=100)
    time = models.TimeField(help_text="Time for quiz in minutes")
    number_of_question = models.IntegerField()
    level = models.CharField(max_length=6,choices=LEVEL)

    class Meta:
        verbose_name_plural:str = "Quizzes"

    def __str__(self):
        return self.name

    def get_questions(self):
        return self.questions.all().order_by("-created")

class Question(models.Model):
    quiz:Quiz = models.ForeignKey(Quiz,related_name="questions",on_delete=models.CASCADE)
    question:str = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question

    def get_answers(self):
        return self.answers.all()

class Answer(models.Model):
    question:Question = models.ForeignKey(Question,related_name="answers",on_delete=models.CASCADE)
    option:str = models.CharField(max_length=200)
    correct:bool = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.option



class Result(models.Model):
    user:User = models.ForeignKey(User,on_delete=models.CASCADE)
    quiz:Quiz = models.ForeignKey(Quiz,on_delete=models.CASCADE)
    score:float = models.FloatField()

    def __str__(self):
        return self.user.username

main/views.py
#third party import 
import json

#django imports
from django.shortcuts import (render,get_object_or_404)
from django.http import HttpRequest,JsonResponse
from django.core.paginator import (Paginator,EmptyPage,PageNotAnInteger)
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView

#my import 
from .models import (Quiz,Question,Answer)


class Quizzes(ListView):
    model = Quiz
    template_name = "main/home.html"


def question(request:HttpRequest,quiz_id):
    quiz = get_object_or_404(Quiz,id=quiz_id)

    questions = quiz.get_questions()

    #questions = Question.objects.filter(quiz=quiz).order_by("question")

    paginator = Paginator(questions,1)
    page_number = request.GET.get("page")
    try:
        page_obj = paginator.get_page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.get_page(1)
    except EmptyPage:
        page_obj = paginator.get_page(num_pages)

    context = {
            "quiz":quiz,
            "page_obj":page_obj,
            }
    return render(request,"main/question.html",context)

#for displaying result
@csrf_exempt
def submit(request:HttpRequest,quiz_id):

    client_answer = json.loads(request.body)
    print(client_answer)

    quiz = get_object_or_404(Quiz,id=quiz_id)
    questions = Question.objects.filter(quiz=quiz)

    server_answer = []

    for question in questions:
        ans = Answer.objects.get(question=question,correct=True)
        server_answer.append(ans.option)

    result = 0
    for i in range(len(client_answer)):
        if client_answer[i] in server_answer:
            result += 1

    data = {"answer":result}

    return JsonResponse(data,content_type="application/json") 

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %} {% endblock %}</title>
   <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
  <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
</head>
<body>
  <div class="navbar">
    <h2 class="logo">
      Django Quiz
    </h2>
    <h2 class="time">start</h2>
  </div>
  
  {% block content %}
  
  {% endblock %}

  <script src="{% static 'main/js/script.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"
        ></script>
</body>
</html>

main/templates/main/home.html
{% extends "main/base.html" %}

{% block title %} Quizzes {% endblock %}

{% block content %}
<h3 id="avail-quiz">Available Quizzes</h3>
<div class="quizzes">
  {% for quiz in object_list %}
  <a href="{% url 'main:question' quiz.id %}" class="quiz">
    {{ quiz.name }}
  </a>
  {% endfor %}
</div>
{% endblock %}

main/templates/main/question.html
{% extends "main/base.html" %}

{% block title %} Question {% endblock %}

{% block content %}
  {% for question in page_obj %}
  <div class="question-div">{{page_obj.number}}. {{ question.question }}
  </div>
  
  <!-- options -->
  <div class="option-div">
    <div class="option">
      <form id="myForm{{question.id}}" action="" method="post">
      {% csrf_token %}
      <input type="hidden" name="question_id" value="{{ question.id }}" id="question_id">
      {% for option in question.get_answers %}
      <div class="input-group">
    <div class="input-group-prepend">
    <div class="input-group-text">
    <input type="radio" id="option{{option.id}}" name="options" value="{{ option.option }}">
    </div>
  </div>
  <label for="option{{option.id}}" class="form-control my-2">{{ option.option }}</label>
</div>
      {% endfor %}
      </form>
    </div>
  </div>
  {% endfor %}
  
  <!-- navigation -->
  <div class="page">        
  {% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}"><button class="btn" id="previous">Previous</button></a>
  {% endif %}
  {% if page_obj.has_previous and not page_obj.has_next%}
    <button id="submit" data-id="{{quiz.id}}" class="btn" onclick="submitAnswers()">Submit</button>
  {% endif %}
  {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}"><button class="btn" id="next">Next</button></a>
      {% endif %}
    </div>
  </div>
{% endblock %}